### ISSUE TITLE
If check then uncheck the fields in clip configuration window, the field is turned out to be black

### ISSUE THREAD

**Issue by HuilanZhang** [LTTPP/Eemory#77]
Environment:
Version: 1.1.0.201508030815
Java: 1.7.0_51
Windows 10
Eclipse Mars

Steps:
1. Authenticate with 印象笔记.
2. Select the Clip Configurations, check the field (Notebook, Note, Tag or Comment) then uncheck.

Observed Behavior:
1. The field is turned out to be black.

Expected Result:
1. The field should be grayed out.

**Comment by liujienwei** [comment]
/*
                 * Workaround for Eclipse Bug 193933: Text is not grayed out
                 * when disabled if custom foreground color is set.
                 */
                text.setBackground(button.getSelection() ? null : shell.getDisplay().getSystemColor(SWT.COLOR_TITLE_INACTIVE_FOREGROUND));

This is a bug introduced by the fix for a Eclipse Bug# 193933 which only happens on Win 7 and earlier versions.

**Comment by liujienwei** [comment]
Fixed.
